spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
